config/routes.rb
Rails.application.routes.draw do
  root :to => 'calendars#home'

  get '/calendars/year' => 'calendars#year'
  get '/calendars/international' => 'calendars#international'
  get '/calendars/international_lists' => 'calendars#international_lists'
  resources :calendars, :only => [:index]

  get '/events/lists' => 'events#lists'
  get '/events/kinds' => 'events#kinds'
  get '/events/kind/:kind' =>'events#kind'
  resources :events

  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # resources :events do
  #   get :lists
  #   get :kinds
  # end

end

#                          root GET    /                                        calendar#home
#                calendars_year GET    /calendars/year(.:format)                calendars#year
#       calendars_international GET    /calendars/international(.:format)       calendars#international
# calendars_international_lists GET    /calendars/international_lists(.:format) calendars#international_lists
#                     calendars GET    /calendars(.:format)                     calendars#index
#                  events_lists GET    /events/lists(.:format)                  events#lists
#                  events_kinds GET    /events/kinds(.:format)                  events#kinds
#                               GET    /events/kind/:kind(.:format)             events#kind
#                        events GET    /events(.:format)                        events#index
#                               POST   /events(.:format)                        events#create
#                     new_event GET    /events/new(.:format)                    events#new
#                    edit_event GET    /events/:id/edit(.:format)               events#edit
#                         event GET    /events/:id(.:format)                    events#show
#                               PATCH  /events/:id(.:format)                    events#update
#                               PUT    /events/:id(.:format)                    events#update
#                               DELETE /events/:id(.:format)                    events#destroy
#                         users GET    /users(.:format)                         users#index
#                               POST   /users(.:format)                         users#create
#                      new_user GET    /users/new(.:format)                     users#new
#                     edit_user GET    /users/:id/edit(.:format)                users#edit
#                          user GET    /users/:id(.:format)                     users#show
#                               PATCH  /users/:id(.:format)                     users#update
#                               PUT    /users/:id(.:format)                     users#update
#                               DELETE /users/:id(.:format)                     users#destroy
#                         login GET    /login(.:format)                         session#new
#                               POST   /login(.:format)                         session#create
#                               DELETE /login(.:format)                         session#destroy

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController

  def home
  end

  def show
     @region = params[:region]
     @date = date_params
     country = Enrico::Country.new("aus", @region)
     @public_holidays = country.public_holidays_for_month(@date)
  end

  def index
  end

  def international
    @country_code = params[:country_code]
    @date = date_params
    country = Enrico::Country.new(@country_code)
    @public_holidays = country.public_holidays_for_month(@date)
  end

  def international_lists
    @country_code = params[:country_code]
    @date = date_params
    country = Enrico::Country.new(@country_code)
    @public_holidays = country.public_holidays_for_year(@date)
  end

  def date_params
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  def home
  end

  def index
     @region = params[:region]
     @date = date_params
     country = Enrico::Country.new("aus", @region)
     @public_holidays = country.public_holidays_for_month(@date)
  end

  def international
    @country_code = params[:country_code]
    @date = date_params
    country = Enrico::Country.new(@country_code)
    @public_holidays = country.public_holidays_for_month(@date)
  end

  def international_lists
    @country_code = params[:country_code]
    @date = date_params
    country = Enrico::Country.new(@country_code)
    @public_holidays = country.public_holidays_for_year(@date)
  end

  def date_params
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/views/calendar/home.html.erb
<h1 id='home_h1'>Plan Your Events! </h1>

<% if @current_user %>
<%= link_to(image_tag('http://i.imgur.com/nDDC2Xx.jpg', :id => 'home_pic'), events_path(date: @date, :region => 'New South Wales'), :title => 'Current Calendar') %>
<% else %>

<%= link_to(image_tag('http://i.imgur.com/nDDC2Xx.jpg', :id => 'home_pic'), calendar_show_path(date: @date, :region => 'New South Wales'), :title => 'Current Calendar') %>
<% end %>

app/views/calendar/show.html.erb
<%= render :partial => 'calendar' %>

<div class="row">
  <div class="col-md-12">

    <%= calendar @date do |date| %>
      <%= date.day  %>
      <div class="day-cell">
<!--////////////////////////////lunar-calanedar////////////////////// -->
        <div class='lunar_calendar'>
        <% solar = date.to_s %>
        <% solar_date_str = solar.gsub(/-/,"") %>
        <% lunar = LunarToSolar.find_by(:solar_date => solar_date_str).lunar_date %>
        <% @solar_data = LunarToSolar.find_by(:lunar_date => lunar ).solar_date %>
        <% @solar = [solar[0,4],solar[4,2],solar[6,2]].join("-") %>
        <% @lunar_str = [lunar[0,4],lunar[4,2],lunar[6,2]].join("-") %>
        <% lunar_date_with_solar = LunarToSolar.find_by(:solar_date => @solar_data).lunar_date %>
        <% solar_data = @solar_data[6,2] %>
        <% @lunar_date = lunar_date_with_solar[4,7] %>
        <% if solar_data.gsub(/^0/,"") == date.day.to_s %>
        <span class ='lunar_calendar'><%= @lunar_date %></span>
        <% end %>
        </div>
<!--///////////////////////public-holiday- calanedar/////////////////// -->
        <div class='public'>
          <% if @public_holidays.present? %>
        <% @public_holidays.each do |holiday| %>
          <% if holiday.date.strftime('%d').gsub(/^0/,'').to_s == date.day.to_s %>

            <p>
                  <% holi_name = holiday.local_name.to_s.split(" ").first %>
                  <%= if holi_name == "New"
                        image_tag('http://i.imgur.com/Sxa1rTl.png?1')
                      elsif holi_name == "Easter"
                        image_tag('http://i.imgur.com/zOhmINw.png?1')
                      elsif holi_name == "Queen's"
                        image_tag('http://i.imgur.com/YRAOZlL.png?1')
                      elsif holi_name == "Christmas"
                        image_tag('http://i.imgur.com/rvGvYSh.png?1')
                      else
                        image_tag('http://i.imgur.com/NxNrPHD.png?1')
                      end %><br/>
                  <%= holiday.local_name.to_s %>
            </p>

          <% end %>
        <% end %>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>