config/routes.rb
Rails.application.routes.draw do
  root :to => 'calendars#home'

  get '/calendars/year' => 'calendars#year'
  get '/calendars/international' => 'calendars#international'
  get '/calendars/international_lists' => 'calendars#international_lists'
  resources :calendars, :only => [:index]

  get '/events/lists' => 'events#lists'
  get '/events/kinds' => 'events#kinds'
  get '/events/kind/:kind' =>'events#kind'
  resources :events

  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # resources :events do
  #   get :lists
  #   get :kinds
  # end

end

#                          root GET    /                                        calendar#home
#                calendars_year GET    /calendars/year(.:format)                calendars#year
#       calendars_international GET    /calendars/international(.:format)       calendars#international
# calendars_international_lists GET    /calendars/international_lists(.:format) calendars#international_lists
#                     calendars GET    /calendars(.:format)                     calendars#index
#                  events_lists GET    /events/lists(.:format)                  events#lists
#                  events_kinds GET    /events/kinds(.:format)                  events#kinds
#                               GET    /events/kind/:kind(.:format)             events#kind
#                        events GET    /events(.:format)                        events#index
#                               POST   /events(.:format)                        events#create
#                     new_event GET    /events/new(.:format)                    events#new
#                    edit_event GET    /events/:id/edit(.:format)               events#edit
#                         event GET    /events/:id(.:format)                    events#show
#                               PATCH  /events/:id(.:format)                    events#update
#                               PUT    /events/:id(.:format)                    events#update
#                               DELETE /events/:id(.:format)                    events#destroy
#                         users GET    /users(.:format)                         users#index
#                               POST   /users(.:format)                         users#create
#                      new_user GET    /users/new(.:format)                     users#new
#                     edit_user GET    /users/:id/edit(.:format)                users#edit
#                          user GET    /users/:id(.:format)                     users#show
#                               PATCH  /users/:id(.:format)                     users#update
#                               PUT    /users/:id(.:format)                     users#update
#                               DELETE /users/:id(.:format)                     users#destroy
#                         login GET    /login(.:format)                         session#new
#                               POST   /login(.:format)                         session#create
#                               DELETE /login(.:format)                         session#destroy

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  date       :date
#  image      :text
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Event < ActiveRecord::Base
  belongs_to :user

  def self.icon_option
   { "Special Day" => [
       ['Anniversary', 'http://i.imgur.com/VfuWprd.png?1'],
       ['Birthday', 'http://i.imgur.com/7NfALqS.png?1'],
       ['Wedding', 'http://i.imgur.com/pEZwa3W.png?1'],
       ['Babyshower', 'http://i.imgur.com/QgyWEnt.png?1'],
       ['Dinner', 'http://i.imgur.com/g2Pa7a9.png?1'],
       ['Party', 'http://i.imgur.com/BIrp93l.png?1'],
       ['Travel', 'http://i.imgur.com/OcIn4ds.png?1'],
       ['Others', 'http://i.imgur.com/tAT8AUw.png?1']
     ],
   "Business" => [
       ['Meeting', 'http://i.imgur.com/VgujmI2.png?1'],
       ['Workshop', 'http://i.imgur.com/q4shvdS.png?1'],
       ['Presentation', 'http://i.imgur.com/f10BbHs.png?1'],
       ['Conference', 'http://i.imgur.com/5PrjrVs.png?1'],
       ['Others', 'http://i.imgur.com/tAT8AUw.png?1']
     ]
   }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
     @region = params[:region]
     # Setting current date dynamically
     @date = date_params
     # Australia needs state(=@region)
     country = Enrico::Country.new("aus", @region)
     # To display public holiday and the user's events together.
     @public_holidays = country.public_holidays_for_month(@date)
     @events = Event.where(:user_id => @current_user.id)
  end

  def create
    event = Event.create event_params
    event.save
    @current_user.events << event
    redirect_to event_path
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find params[:id]
    unless @event.user_id == @current_user.id
      redirect_to root_path
    end
  end

  def lists
    @date = date_params
    @events = Event.where(:user_id => @current_user.id).order(:date).reverse
    # @past_events = @events[:date] < @date
    # @future_events = @events[:date] > @date
    country = Enrico::Country.new("aus", "New South Wales")
    @public_holidays = country.public_holidays_for_year(@date)
  end

  def kind
    # Insead of Creating a new table I wrote this....
    # I agree it is not the best way but it was my first project!!
    # I don't want change this but keep it as a memory lol!
    image = case params[:kind]
      when 'Birthday' then 'http://i.imgur.com/7NfALqS.png?1'
      when 'Anniversary' then 'http://i.imgur.com/VfuWprd.png?1'
      when 'Wedding' then 'http://i.imgur.com/pEZwa3W.png?1'
      when 'Babyshower' then 'http://i.imgur.com/QgyWEnt.png?1'
      when 'Dinner' then 'http://i.imgur.com/g2Pa7a9.png?1'
      when 'Party' then 'http://i.imgur.com/BIrp93l.png?1'
      when 'Travel' then 'http://i.imgur.com/OcIn4ds.png?1'
      when 'Meeting' then 'http://i.imgur.com/VgujmI2.png?1'
      when 'Workshop' then 'http://i.imgur.com/q4shvdS.png?1'
      when 'Presentation' then 'http://i.imgur.com/f10BbHs.png?1'
      when 'Conference' then 'http://i.imgur.com/5PrjrVs.png?1'
      when 'Others' then 'http://i.imgur.com/tAT8AUw.png?1'
    end
    @events = Event.where(:user_id => @current_user.id, :image => image)
    render :kinds
  end

  def kinds
    @events = Event.where(:user_id => @current_user.id)
  end

  def show
    @event = Event.find params[:id]

  end

  def update
    event = Event.find params[:id]
    event.update event_params
    event.save

    redirect_to event_path
  end

  def destroy
    event = Event.find params[:id]
    event.destroy

    redirect_to events_path
  end

  private
  def date_params
    # It is a way to set current day dynamically
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def event_params
    params.require(:event).permit(:name, :date, :image, :user_id)
  end

end

app/views/events/_calendar.html.erb
<div class='aus_state'>
  <%= link_to 'NSW', events_path(date: @date, :region => 'New South Wales') %>
  <%= link_to 'VIC', events_path(date: @date, :region => 'Victoria') %>
  <%= link_to 'QLD', events_path(date: @date, :region => 'Queensland') %>
  <%= link_to 'WA', events_path(date: @date, :region => 'Western Australia') %>
  <%= link_to 'SA', events_path(date: @date, :region => 'South Australia') %>
  <%= link_to 'ACT', events_path(date: @date, :region => 'Australian Capital Territory') %>
  <%= link_to 'TAS', events_path(date: @date, :region => 'Tasmania') %>
  <%= link_to 'NT', events_path(date: @date, :region => 'Northern Territory') %>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">

      <%= link_to events_path(date: @date - 12.month, :region => @region) do %>
        <i><%=image_tag('http://i.imgur.com/9GN8wMm.png?1')%></i>
      <% end %>

      <%= link_to events_path(date: @date - 1.month, :region => @region) do %>
        <i ><%= image_tag("http://i.imgur.com/ca2RSq3.png?1")%></i>
      <% end %>

      <span id='current_calendar_date'><%= "#{@date.strftime("%B")} #{@date.year}" %></span>

      <%= link_to events_path(date: @date + 1.month, :region => @region) do %>
        <i ><%= image_tag('http://i.imgur.com/obLPimz.png?1')%></i>
      <% end %>

      <%= link_to events_path(date: @date + 12.month, :region => @region) do %>
        <i><%= image_tag('http://i.imgur.com/ErCSqCA.png?1')%></i>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_events-calendar.html.erb
<div class='aus_state'>
  <% Regions.state.each do |state| %>
    <% state.each do |key, val| %>
      <%= link_to key, events_path(date: @date, :region => val) %>
    <% end %>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">

      <%= link_to events_path(date: @date - 12.month, :region => @region) do %>
        <i><%=image_tag('http://i.imgur.com/9GN8wMm.png?1')%></i>
      <% end %>

      <%= link_to events_path(date: @date - 1.month, :region => @region) do %>
        <i ><%= image_tag("http://i.imgur.com/ca2RSq3.png?1")%></i>
      <% end %>

      <span id='current_calendar_date'><%= "#{@date.strftime("%B")} #{@date.year}" %></span>

      <%= link_to events_path(date: @date + 1.month, :region => @region) do %>
        <i ><%= image_tag('http://i.imgur.com/obLPimz.png?1')%></i>
      <% end %>

      <%= link_to events_path(date: @date + 12.month, :region => @region) do %>
        <i><%= image_tag('http://i.imgur.com/ErCSqCA.png?1')%></i>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_eventscalendar.html.erb
<div class='aus_state'>
  <% Regions.state.each do |state| %>
    <% state.each do |key, val| %>
      <%= link_to key, events_path(date: @date, :region => val) %>
    <% end %>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <!-- Link to A YEAR AGO -->
      <%= link_to events_path(date: @date - 12.month, :region => @region) do %>
        <i><%=image_tag('http://i.imgur.com/9GN8wMm.png?1')%></i>
      <% end %>

       <!-- Link to A MONTH AGO -->
      <%= link_to events_path(date: @date - 1.month, :region => @region) do %>
        <i ><%= image_tag("http://i.imgur.com/ca2RSq3.png?1")%></i>
      <% end %>

       <!-- Display Current Date -->
      <span id='current_calendar_date'><%= "#{ @date.strftime("%B") } #{ @date.year }" %></span>

       <!-- Link to A MONTH LATER -->
      <%= link_to events_path(date: @date + 1.month, :region => @region) do %>
        <i ><%= image_tag('http://i.imgur.com/obLPimz.png?1')%></i>
      <% end %>

       <!-- Link to A YEAR LATER -->
      <%= link_to events_path(date: @date + 12.month, :region => @region) do %>
        <i><%= image_tag('http://i.imgur.com/ErCSqCA.png?1')%></i>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class='event_form'>
  <%= form_for @event do |f| %>
    <p>
      <%= f.label :image, "Icon" %><br/>
      <%= f.select :image, grouped_options_for_select(Event.icon_option) %>
    </p>

    <p>
      <%= f.label :name, 'Title' %><br/>
      <%= f.text_field :name, :autofocus => true %>
    </p>

    <p>
      <%= f.label :date %><br/>
      <%= f.date_field :date %>
    </p>

    <%= f.submit 'Submit', :class => 'submit' %>
<% end %>
</div>

app/views/events/edit.html.erb
<h1>Edit The Event Details</h1>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%= render :partial => 'eventscalendar' %>

<div class="row">
  <div class="col-md-12">
    <%= calendar @date do |date| %>
      <%= date.day  %>
      <div class="day-cell">

<!--##### lunar-calanedar ##### -->

        <div class ='lunar_calendar'>
           <!-- Making today's date to the string -->
          <% solar = date.to_s %>
           <!-- Solar string is 'YYYY-MM-DD',
           but it needed to be 'YYYYMMDD' to compare to lunar dates
           in CSV file that pushed into LunarToSolar table -->
          <% solar_date_str = solar.gsub(/-/,"") %>
           <!-- Finding the lunar date -->
          <% lunar = LunarToSolar.find_by(:solar_date => solar_date_str).lunar_date %>
           <!-- Finding the solar date -->
          <% @solar_data = LunarToSolar.find_by(:lunar_date => lunar ).solar_date %>
           <!-- Changing back 'YYYYMMDD' to 'YYYY-MM-DD' to use Date class -->
          <% @solar = [solar[0,4],solar[4,2],solar[6,2]].join("-") %>
          <% @lunar_str = [lunar[0,4],lunar[4,2],lunar[6,2]].join("-") %>

          <% lunar_date_with_solar = LunarToSolar.find_by(:solar_date => @solar_data).lunar_date %>
           <!-- Grab Only DD(date) to display in the month calendar -->
          <% solar_data = @solar_data[6,2] %>
          <% @lunar_date = lunar_date_with_solar[4,7] %>
            <!-- /^0/ : Delete only first Zero.
               because date's single number of day is without Zero
               ex) 2014-05-01's day is 1.  -->
          <% if solar_data.gsub(/^0/,"") == date.day.to_s %>
            <span class ='lunar_calendar'><%= @lunar_date %><span>
          <% end %>
        </div>

<!-- ##### public-holiday-calanedar ##### -->

        <div class='public'>
          <% if @public_holidays.present? %>
            <% @public_holidays.each do |holiday| %>
               <!-- /^0/ : Delete only first Zero.
               because date's single number of day is without Zero
               ex) 2014-05-01's day is 1.  -->
              <% if holiday.date.strftime('%d').gsub(/^0/,'').to_s == date.day.to_s %>

                <p><!-- Set icons for World-Famous Holiday
                    ex) Christmas -->
                  <% holi_name = holiday.local_name.to_s.split(" ").first %>
                  <%= if holi_name == "New"
                        image_tag('http://i.imgur.com/Sxa1rTl.png?1')
                      elsif holi_name == "Easter"
                        image_tag('http://i.imgur.com/zOhmINw.png?1')
                      elsif holi_name == "Queen's"
                        image_tag('http://i.imgur.com/YRAOZlL.png?1')
                      elsif holi_name == "Christmas"
                         image_tag('http://i.imgur.com/rvGvYSh.png?1')
                      else
                         image_tag('http://i.imgur.com/NxNrPHD.png?1')
                      end %><br/>
                  <%= holiday.local_name.to_s %>
                </p>
              <% end %>
            <% end %>
          <% end %>
        </div>

<!--////////////////////////////event-calanedar////////////////////// -->

        <!-- Display Personal Event if there is any  -->
        <% if @events.present? %>
          <% @events.each do |event| %>
            <% if event.date == date %>
              <p>
                <%= image_tag(event.image) %><br/>
                <%= link_to event.name, event %>
              </p>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

app/views/events/kinds.html.erb
<% if @events.present? %>
  <h1>Events for <%= params[:kind] %></h1>
    <% @events.each do |event| %>
      <p>
        <%= image_tag(event.image)%> <%= event.name %>
        (<%= link_to(event.date, events_path(date: event.date, :region => @region)) %>)
      </p>
    <% end %>
<% else %>
  <h4> You don't have any events :) </h4>
<% end %>

<div class='show_options'>
  <p><%= link_to('Back', events_lists_path)%></p>
</div>

app/views/events/lists.html.erb
<p id='kind'>Personal Events</p>
<div class='icon_description'>
   <!-- Wrote every single events kind and it's routes.....
    I now agree it is not the best way but it was my first project!!! lol -->
  <p><%= link_to(image_tag('http://i.imgur.com/VfuWprd.png?1', :title => 'Anniversary'),'/events/kind/Anniversary')%><br/>Anniversary</p>
  <p><%= link_to(image_tag('http://i.imgur.com/7NfALqS.png?1', :title => 'Birthday'), '/events/kind/Birthday') %><br/>Birthday</p>
  <p><%= link_to(image_tag('http://i.imgur.com/pEZwa3W.png?1', :title => 'Wedding'), '/events/kind/Wedding')%><br/>Wedding</p>
  <p><%= link_to(image_tag('http://i.imgur.com/QgyWEnt.png?1', :title => 'Babyshower'),'/events/kind/Babyshower')%><br/>Babyshower</p>
  <p><%= link_to(image_tag('http://i.imgur.com/g2Pa7a9.png?1', :title => 'Dinner'),'/events/kind/Dinner')%><br/>Dinner</p>
  <p><%= link_to(image_tag('http://i.imgur.com/BIrp93l.png?1', :title => 'Party'),'/events/kind/Party')%><br/>Party</p>
  <p><%= link_to(image_tag('http://i.imgur.com/OcIn4ds.png?1', :title => 'Travel'),'/events/kind/Travel')%><br/>Travel</p>

  <p><%= link_to(image_tag('http://i.imgur.com/VgujmI2.png?1', :title => 'Meeting'),'/events/kind/Meeting')%><br/>Meeting</p>
  <p><%= link_to(image_tag('http://i.imgur.com/q4shvdS.png?1', :title => 'Workshop'),'/events/kind/Workshop')%><br/>Workshop</p>
  <p><%= link_to(image_tag('http://i.imgur.com/f10BbHs.png?1', :title => 'Presentation'),'/events/kind/Presentation')%><br/>Presentation</p>
  <p><%= link_to(image_tag('http://i.imgur.com/5PrjrVs.png?1', :title => 'Conference'),'/events/kind/Conference')%><br/>Conference</p>
  <p><%= link_to(image_tag('http://i.imgur.com/tAT8AUw.png?1', :title => 'Others'),'/events/kind/others')%><br/>Others</p>
</div>

<p id='kind'>Public Holiday</p>
<div class='icon_description'>
  <p><%= image_tag('http://i.imgur.com/Sxa1rTl.png?1')%><br/>New Year</p>
  <p><%= image_tag('http://i.imgur.com/zOhmINw.png?1')%><br/>Easter</p>
  <p><%= image_tag('http://i.imgur.com/YRAOZlL.png?1')%><br/>Qeen's Birthday</p>
  <p><%= image_tag('http://i.imgur.com/rvGvYSh.png?1')%><br/>Christmas</p>
  <p><%= image_tag('http://i.imgur.com/NxNrPHD.png?1')%><br/>Others</p>
</div>

<div class='list' >

<div class='Events_list'>
  <h1>Your Events</h1>
  <ol>
  <% @events.each do |event| %>
    <li><%= image_tag(event.image) %><br/>
      <%= link_to('Details', event) %><%= event.name %>(<%= link_to(event.date, events_path(date: event.date, :region => "New South Wales"))%>)
    </li>
  <% end %>
  </ol>
</div>

<div class='Public_holiday_list'>
  <h1>Public Holiday</h1>
   <ol>
    <% @public_holidays.each do |holiday| %>
      <!-- Set icons for World-Famous Holiday ex) Christmas -->
      <li><% holi_name = holiday.local_name.to_s.split(" ").first %>
        <%  if holi_name == "New"
              holiday_image ='http://i.imgur.com/Sxa1rTl.png?1'
            elsif holi_name == "Easter"
              holiday_image = 'http://i.imgur.com/zOhmINw.png?1'
            elsif holi_name == "Queen's"
              holiday_image = 'http://i.imgur.com/YRAOZlL.png?1'
            elsif holi_name == "Christmas"
              holiday_image = 'http://i.imgur.com/rvGvYSh.png?1'
            else
              holiday_image = 'http://i.imgur.com/NxNrPHD.png?1'
            end %>

        <%= image_tag(holiday_image) %>
        <%= holiday.local_name.to_s %>
        (<%= link_to(holiday.date, events_path(date: holiday.date, :region => "New South Wales"))%>)
      </li>
   <% end %>
  </ol>
 </div>
</div>

app/views/events/new.html.erb
<h1>Create A New Event</h1>
<p id='kind'>Event Icons</p>
<div class ='icon_description'>
  <p><%= image_tag('http://i.imgur.com/VfuWprd.png?1')%><br/>Anniversary</p>
  <p><%= image_tag('http://i.imgur.com/7NfALqS.png?1')%><br/>Birthday</p>
  <p><%= image_tag('http://i.imgur.com/pEZwa3W.png?1')%><br/>Wedding</p>
  <p><%= image_tag('http://i.imgur.com/QgyWEnt.png?1')%><br/>Babyshower</p>
  <p><%= image_tag('http://i.imgur.com/g2Pa7a9.png?1')%><br/>Dinner</p>
  <p><%= image_tag('http://i.imgur.com/BIrp93l.png?1')%><br/>Party</p>
  <p><%= image_tag('http://i.imgur.com/OcIn4ds.png?1')%><br/>Travel</p>

  <p><%= image_tag('http://i.imgur.com/VgujmI2.png?1')%><br/>Meeting</p>
  <p><%= image_tag('http://i.imgur.com/q4shvdS.png?1')%><br/>Workshop</p>
  <p><%= image_tag('http://i.imgur.com/f10BbHs.png?1')%><br/>Presentation</p>
  <p><%= image_tag('http://i.imgur.com/5PrjrVs.png?1')%><br/>Conference</p>
  <p><%= image_tag('http://i.imgur.com/tAT8AUw.png?1')%><br/>Others</p>
</div>

<%= render :partial => 'form' %>

app/views/events/show.html.erb
<div class='event_details'>
  <h1><%= @current_user.username %>'s Event Details</h1>
  <p><%= image_tag(@event.image) %>  Title : <strong><%= @event.name %></strong> | Date : <%= link_to(@event.date, events_path(date: @event.date, :region => @region)) %></p>

  <div class='show_options'>
    <p><%= link_to('Edit', edit_event_path)%></p>
    <p><%= link_to('Delete', events_lists_path, :data => { :confirm => 'Are you sure you want to delete this?', :method => :delete })%></p>
    <p><%= link_to('Create Another Event', new_event_path) %></p>
    <p><%= link_to('Your Events list', events_lists_path) %></p>
  </div>
</div>