config/routes.rb
Rails.application.routes.draw do
  root :to => 'calendars#home'

  get '/calendars/year' => 'calendars#year'
  get '/calendars/international' => 'calendars#international'
  get '/calendars/international_lists' => 'calendars#international_lists'
  resources :calendars, :only => [:index]

  get '/events/lists' => 'events#lists'
  get '/events/kinds' => 'events#kinds'
  get '/events/kind/:kind' =>'events#kind'
  resources :events

  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # resources :events do
  #   get :lists
  #   get :kinds
  # end

end

#                          root GET    /                                        calendar#home
#                calendars_year GET    /calendars/year(.:format)                calendars#year
#       calendars_international GET    /calendars/international(.:format)       calendars#international
# calendars_international_lists GET    /calendars/international_lists(.:format) calendars#international_lists
#                     calendars GET    /calendars(.:format)                     calendars#index
#                  events_lists GET    /events/lists(.:format)                  events#lists
#                  events_kinds GET    /events/kinds(.:format)                  events#kinds
#                               GET    /events/kind/:kind(.:format)             events#kind
#                        events GET    /events(.:format)                        events#index
#                               POST   /events(.:format)                        events#create
#                     new_event GET    /events/new(.:format)                    events#new
#                    edit_event GET    /events/:id/edit(.:format)               events#edit
#                         event GET    /events/:id(.:format)                    events#show
#                               PATCH  /events/:id(.:format)                    events#update
#                               PUT    /events/:id(.:format)                    events#update
#                               DELETE /events/:id(.:format)                    events#destroy
#                         users GET    /users(.:format)                         users#index
#                               POST   /users(.:format)                         users#create
#                      new_user GET    /users/new(.:format)                     users#new
#                     edit_user GET    /users/:id/edit(.:format)                users#edit
#                          user GET    /users/:id(.:format)                     users#show
#                               PATCH  /users/:id(.:format)                     users#update
#                               PUT    /users/:id(.:format)                     users#update
#                               DELETE /users/:id(.:format)                     users#destroy
#                         login GET    /login(.:format)                         session#new
#                               POST   /login(.:format)                         session#create
#                               DELETE /login(.:format)                         session#destroy

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController

  def home
  end

  def show
     @region = params[:region]
     @date = date_params
     country = Enrico::Country.new("aus", @region)
     @public_holidays = country.public_holidays_for_month(@date)
  end

  def index
  end

  def international
    @country_code = params[:country_code]
    @date = date_params
    country = Enrico::Country.new(@country_code)
    @public_holidays = country.public_holidays_for_month(@date)
  end

  def international_lists
    @country_code = params[:country_code]
    @date = date_params
    country = Enrico::Country.new(@country_code)
    @public_holidays = country.public_holidays_for_year(@date)
  end

  def date_params
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  def home
  end

  def index
     @region = params[:region]
     @date = date_params
     country = Enrico::Country.new("aus", @region)
     @public_holidays = country.public_holidays_for_month(@date)
  end

  def international
    @country_code = params[:country_code]
    @date = date_params
    country = Enrico::Country.new(@country_code)
    @public_holidays = country.public_holidays_for_month(@date)
  end

  def international_lists
    @country_code = params[:country_code]
    @date = date_params
    country = Enrico::Country.new(@country_code)
    @public_holidays = country.public_holidays_for_year(@date)
  end

  def date_params
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/views/calendars/_calendar.html.erb
<div class='aus_state'>
  <% Regions.state.each do |state| %>
    <% state.each do |key, val| %>
      <%= link_to key, events_path(date: @date, :region => val) %>
    <% end %>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <div class="arrows">

      <!-- Link to A YEAR AGO -->
      <%= link_to calendars_path(date: @date - 12.month, :region => @region) do %>
        <i><%=image_tag('http://i.imgur.com/9GN8wMm.png?1')%></i>
      <% end %>

       <!-- Link to A MONTH AGO -->
      <%= link_to calendars_path(date: @date - 1.month, :region => @region) do %>
        <i><%= image_tag("http://i.imgur.com/ca2RSq3.png?1")%></i>
      <% end %>

       <!-- Display Current Date -->
      <span id='current_calendar_date'><%= "#{@date.strftime("%B")} #{@date.year}" %></span>

       <!-- Link to A MONTH LATER -->
      <%= link_to calendars_path(date: @date + 1.month, :region => @region) do %>
        <i ><%= image_tag('http://i.imgur.com/obLPimz.png?1')%></i>
      <% end %>

       <!-- Link to A YEAR LATER -->
      <%= link_to calendars_path(date: @date + 12.month, :region => @region) do %>
        <i><%= image_tag('http://i.imgur.com/ErCSqCA.png?1')%></i>
      <% end %>
    </div>
  </div>
</div>

app/views/calendars/_international.html.erb
<div class='int_country'>
  <% Regions.country.each do |country| %>
    <% country.each do |name, code| %>
      <%= link_to name, calendars_international_path(date: @date, country_code: code) %>
    <% end %>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <div class="arrows">

      <!-- Link to A YEAR AGO -->
      <%= link_to calendars_international_path(date: @date - 12.month, country_code: @country_code ) do %>
        <i><%=image_tag('http://i.imgur.com/9GN8wMm.png?1')%></i>
      <% end %>

      <!-- Link to A MONTH AGO -->
      <%= link_to calendars_international_path(date: @date - 1.month, country_code: @country_code) do %>
        <i><%= image_tag("http://i.imgur.com/ca2RSq3.png?1")%></i>
      <% end %>

      <!-- Display Current Date -->
      <span id='current_calendar_date'><%= "#{@date.strftime("%B")} #{@date.year}" %></span>

      <!-- Link to A MONTH LATER -->
      <%= link_to calendars_international_path(date: @date + 1.month, country_code: @country_code) do %>
        <i ><%= image_tag('http://i.imgur.com/obLPimz.png?1')%></i>
      <% end %>

       <!-- Link to A YEAR LATER -->
      <%= link_to calendars_international_path(date: @date + 12.month, country_code: @country_code) do %>
        <i><%= image_tag('http://i.imgur.com/ErCSqCA.png?1')%></i>
      <% end %>

      <!-- Link to INTERNATIONAL HOLIDAY LIST!-->
      <div class='int_list_link'>
        <%= link_to('International Public Holiday List', calendars_international_lists_path(date: @date, country_code: @country_code )) %>
      </div>
    </div>
  </div>
</div>

app/views/calendars/home.html.erb
<h1 id='home_h1'>Plan Your Events with Solar & Lunar Dates! </h1>

<% if @current_user %>
<%= link_to(image_tag('http://i.imgur.com/nDDC2Xx.jpg', :id => 'home_pic'), events_path(date: @date, :region => 'New South Wales'), :title => 'Current Calendar') %>
<% else %>

<%= link_to(image_tag('http://i.imgur.com/nDDC2Xx.jpg', :id => 'home_pic'), calendars_path(date: @date, :region => 'New South Wales'), :title => 'Current Calendar') %>
<% end %>

app/views/calendars/index.html.erb
<%= render :partial => 'calendar' %>

<div class="row">
  <div class="col-md-12">

    <%= calendar @date do |date| %>
      <%= date.day  %>
      <div class="day-cell">

<!--####### lunar-calanedar #######-->
        <div class ='lunar_calendar'>
           <!-- Making today's date to the string -->
          <% solar = date.to_s %>
           <!-- Solar string is 'YYYY-MM-DD',
           but it needed to be 'YYYYMMDD' to compare to lunar dates
           in CSV file that pushed into LunarToSolar table -->
          <% solar_date_str = solar.gsub(/-/,"") %>
           <!-- Finding the lunar date -->
          <% lunar = LunarToSolar.find_by(:solar_date => solar_date_str).lunar_date %>
           <!-- Finding the solar date -->
          <% @solar_data = LunarToSolar.find_by(:lunar_date => lunar ).solar_date %>
           <!-- Changing back 'YYYYMMDD' to 'YYYY-MM-DD' to use Date class -->
          <% @solar = [solar[0,4],solar[4,2],solar[6,2]].join("-") %>
          <% @lunar_str = [lunar[0,4],lunar[4,2],lunar[6,2]].join("-") %>

          <% lunar_date_with_solar = LunarToSolar.find_by(:solar_date => @solar_data).lunar_date %>
           <!-- Grab Only DD(date) to display in the month calendar -->
          <% solar_data = @solar_data[6,2] %>
          <% @lunar_date = lunar_date_with_solar[4,7] %>
            <!-- /^0/ : Delete only first Zero.
               because date's single number of day is without Zero
               ex) 2014-05-01's day is 1.  -->
          <% if solar_data.gsub(/^0/,"") == date.day.to_s %>
            <span class ='lunar_calendar'><%= @lunar_date %><span>
          <% end %>
        </div>

<!--####### public-holiday- calanedar #######-->
        <div class='public'>
          <% if @public_holidays.present? %>
            <% @public_holidays.each do |holiday| %>
              <!-- /^0/ : Delete only first Zero.
               because date's single number of day is without Zero
               ex) 2014-05-01's day is 1.  -->
              <% if holiday.date.strftime('%d').gsub(/^0/,'').to_s == date.day.to_s %>

                <p> <!-- Set icons for World-Famous Holiday
                    ex) Christmas -->
                  <% holi_name = holiday.local_name.to_s.split(" ").first %>
                  <%= if holi_name == "New"
                        image_tag('http://i.imgur.com/Sxa1rTl.png?1')
                      elsif holi_name == "Easter"
                        image_tag('http://i.imgur.com/zOhmINw.png?1')
                      elsif holi_name == "Queen's"
                        image_tag('http://i.imgur.com/YRAOZlL.png?1')
                      elsif holi_name == "Christmas"
                        image_tag('http://i.imgur.com/rvGvYSh.png?1')
                      else
                        image_tag('http://i.imgur.com/NxNrPHD.png?1')
                      end %><br/>
                  <%= holiday.local_name.to_s %>
                </p>

              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/calendars/international.html.erb
<%= render :partial => 'international'%>

<div class="row">
  <div class="col-md-12">
    <%= calendar @date do |date| %>
      <%= date.day  %>
      <div class="day-cell">

<!--####### lunar-calanedar ####### -->
        <div class ='lunar_calendar'>
           <!-- Making today's date to the string -->
          <% solar = date.to_s %>
           <!-- Solar string is 'YYYY-MM-DD',
           but it needed to be 'YYYYMMDD' to compare to lunar dates
           in CSV file that pushed into LunarToSolar table -->
          <% solar_date_str = solar.gsub(/-/,"") %>
           <!-- Finding the lunar date -->
          <% lunar = LunarToSolar.find_by(:solar_date => solar_date_str).lunar_date %>
           <!-- Finding the solar date -->
          <% @solar_data = LunarToSolar.find_by(:lunar_date => lunar ).solar_date %>
           <!-- Changing back 'YYYYMMDD' to 'YYYY-MM-DD' to use Date class -->
          <% @solar = [solar[0,4],solar[4,2],solar[6,2]].join("-") %>
          <% @lunar_str = [lunar[0,4],lunar[4,2],lunar[6,2]].join("-") %>

          <% lunar_date_with_solar = LunarToSolar.find_by(:solar_date => @solar_data).lunar_date %>
           <!-- Grab Only DD(date) to display in the month calendar -->
          <% solar_data = @solar_data[6,2] %>
          <% @lunar_date = lunar_date_with_solar[4,7] %>
            <!-- /^0/ : Delete only first Zero.
               because date's single number of day is without Zero
               ex) 2014-05-01's day is 1.  -->
          <% if solar_data.gsub(/^0/,"") == date.day.to_s %>
            <span class ='lunar_calendar'><%= @lunar_date %><span>
          <% end %>
        </div>

<!--####### public-holiday-calanedar #######-->
        <div class='public'>
          <% if @public_holidays.present? %>
            <% @public_holidays.each do |holiday| %>
              <!-- /^0/ : Delete only first Zero.
               because date's single number of day is without Zero
               ex) 2014-05-01's day is 1.  -->
              <% if holiday.date.strftime('%d').gsub(/^0/,'').to_s == date.day.to_s %>
                <p><!-- Set icons for World-Famous Holiday
                    ex) Christmas -->
                  <% holi_name = holiday.english_name.to_s.split(" ").first %>
                    <%= if holi_name == "New"
                          image_tag('http://i.imgur.com/Sxa1rTl.png?1')
                        elsif holi_name == "Easter"
                          image_tag('http://i.imgur.com/zOhmINw.png?1')
                        elsif holi_name == "Queen's"
                          image_tag('http://i.imgur.com/YRAOZlL.png?1')
                        elsif holi_name == "Christmas"
                          image_tag('http://i.imgur.com/rvGvYSh.png?1')
                        else
                          image_tag('http://i.imgur.com/NxNrPHD.png?1')
                        end %><br/>
                  <!-- Display the holiday's local name
                    unless it is same as Enlgish name -->
                  <span class='holi_local'><%= holiday.local_name.to_s %></span><br/><%= holiday.english_name.to_s if holiday.local_name != holiday.english_name %>
                </p>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/calendars/international_lists.html.erb
<div class='int_country'>
  <% Regions.country.each do |country| %>
    <% country.each do |name, code| %>
      <%= link_to name, calendars_international_path(date: @date, country_code: code) %>
    <% end %>
  <% end %>
</div>


<div class='int_Public_holiday_list'>
  <h1>Public Holiday</h1>
   <ol>
    <% @public_holidays.each do |holiday| %>
      <li><% holi_name = holiday.english_name.to_s.split(" ").first %>
        <!-- Set icons for World-Famous Holiday ex) Christmas -->
        <%  if holi_name == "New"
              holiday_image ='http://i.imgur.com/Sxa1rTl.png?1'
            elsif holi_name == "Easter"
                holiday_image = 'http://i.imgur.com/zOhmINw.png?1'
            elsif holi_name == "Queen's"
                holiday_image = 'http://i.imgur.com/YRAOZlL.png?1'
            elsif holi_name == "Christmas"
                holiday_image = 'http://i.imgur.com/rvGvYSh.png?1'
            else
                holiday_image = 'http://i.imgur.com/NxNrPHD.png?1'
            end %>
        <%= image_tag(holiday_image) %>

        <!-- Link to the actual date in the seletect country's calendar -->
        <%= holiday.english_name %> (<%= link_to(holiday.date, calendars_international_path(date: holiday.date, :country_code => @country_code))%>)<br/>
        <p id='local_name'>Local Name : <%= holiday.local_name.to_s %>
      </li>
    <% end %>
  </ol>
</div>